apiVersion: 1

datasources:
  - name: PostgreSQL
    type: grafana-postgresql-datasource
    uid: postgres-telemetry
    access: proxy
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    database: telemetrydb
    user: postgres
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
    isDefault: true
